const dimensions = {
  strategy: {
    label: "Strategy and Leadership",
    points: 20,
    recommendation:
      "Clarify ownership, tie AI work to GTM priorities, and make progress part of the regular executive operating rhythm.",
  },
  workflow: {
    label: "Workflow Operationalization",
    points: 24,
    gate: true,
    recommendation:
      "Move from isolated use cases to repeatable AI-enabled workflows, stronger data readiness, and cross-GTM orchestration.",
  },
  talent: {
    label: "Talent and Change Readiness",
    points: 16,
    recommendation:
      "Build role clarity, practical enablement, workflow libraries, and change management for teams still outside the AI motion.",
  },
  governance: {
    label: "Governance and Investment Discipline",
    points: 18,
    gate: true,
    recommendation:
      "Document governance, define risk-based oversight, and add disciplined investment and buy/build decision criteria.",
  },
  measurement: {
    label: "Measurement and Business Impact",
    points: 22,
    gate: true,
    recommendation:
      "Instrument AI-enabled workflows so adoption, productivity, workflow performance, capacity, and business outcomes can guide decisions.",
  },
};

const sections = [
  {
    id: "company",
    label: "Company Profile",
    questions: [
      {
        id: "company_industry",
        short: "Q1",
        title: "Select the industry that best describes your company:",
        type: "radio",
        required: true,
        options: [
          "B2B SaaS",
          "AI-Native Software",
          "B2B Services",
          "Manufacturing",
          "Financial Services",
          "Other",
        ],
      },
      {
        id: "company_revenue",
        short: "Q2",
        title: "Select the total revenue for your last fiscal year:",
        type: "radio",
        required: true,
        options: [
          "< $10M",
          "$10M - $20M",
          "$20M - $50M",
          "$50M - $100M",
          "$100M - $250M",
          "$250M - $500M",
          "$500M - $1B",
          "> $1B",
        ],
      },
      {
        id: "company_acv",
        short: "Q3",
        title: "Select the average annual contract value:",
        type: "radio",
        required: true,
        options: [
          "< $1K",
          "$1K - $5K",
          "$5K - $10K",
          "$10K - $25K",
          "$25K - $50K",
          "$50K - $100K",
          "$100K - $250K",
          "$250K - $1M",
          "> $1M",
        ],
      },
      {
        id: "company_gtm",
        short: "Q4",
        title: "Select your primary go-to-market model:",
        type: "radio",
        required: true,
        options: ["Sales-led (SLG)", "Product-led (PLG)", "Hybrid (PLG + Sales)"],
      },
      {
        id: "company_funding",
        short: "Q5",
        title: "How is your company funded?",
        type: "radio",
        required: true,
        options: [
          "Bootstrapped",
          "Venture-backed",
          "Private equity-backed",
          "Publicly traded",
        ],
      },
    ],
  },
  {
    id: "strategy",
    label: "Strategy (20)",
    questions: [
      scoredRadio(
        "q1_owner",
        "Q6",
        "Who owns Marketing AI strategy and execution today?",
        "strategy",
        7,
        [
          "No clear owner",
          "Individual contributors or informal champions",
          "Marketing team leaders",
          "CMO or senior Marketing leadership",
          "Cross-functional GTM or executive leadership group",
        ],
      ),
      scoredRadio(
        "q2_alignment",
        "Q7",
        "Which best describes how Marketing AI priorities are set?",
        "strategy",
        7,
        [
          "Based mainly on individual experimentation",
          "Based on team-level opportunities",
          "Based on selected Marketing priorities",
          "Based on defined GTM or company objectives",
          "Reviewed as part of planning, budget, and operating decisions",
        ],
      ),
      scoredRadio(
        "q3_review",
        "Q8",
        "How often is Marketing AI progress reviewed with executive or GTM leadership?",
        "strategy",
        6,
        [
          "Rarely or never",
          "Occasionally",
          "Quarterly or during planning cycles",
          "Regularly as part of Marketing or GTM operating reviews",
          "As a standing executive agenda item with decisions, owners, and follow-up actions",
        ],
      ),
      {
        id: "q4_lens",
        short: "Q9",
        title:
          "What is the primary business lens through which your company views AI investment in Marketing?",
        helper: "Rank from highest to lowest priority.",
        type: "rank",
        required: true,
        scoringLabel: "Unscored benchmark",
        options: [
          "Increased productivity",
          "Reduced costs",
          "Speed to market",
          "Pipeline generation",
          "Revenue growth",
          "Competitive differentiation",
          "Business transformation",
        ],
      },
      {
        id: "q5_self",
        short: "Q10",
        title: "Which statement best reflects your Marketing organization's use of AI today?",
        type: "radio",
        required: true,
        perception: true,
        scoringLabel: "Unscored perception gap",
        options: [
          "We are experimenting with AI tools through individual use and limited coordination",
          "We are using AI in some repeatable workflows, but adoption is not yet scaled",
          "We are standardizing AI across teams and core Marketing workflows",
          "We have redesigned meaningful parts of our GTM motion with AI-enabled workflows, new operating practices, and measurable impact",
        ],
      },
    ],
  },
  {
    id: "workflow",
    label: "Workflow (24)",
    questions: [
      {
        id: "q6_functions",
        short: "Q11",
        title: "Which Marketing functions or program areas use AI in a repeatable way today?",
        helper: "Select all that apply.",
        type: "checkbox",
        required: true,
        dimension: "workflow",
        weight: 4,
        scoreFn: scoreFunctionsBreadth,
        options: [
          "Content",
          "Demand generation",
          "AEO / GEO / LLM discovery",
          "ABM",
          "Analytics and reporting",
          "Data management",
          "Sales enablement",
          "Customer marketing",
          "None",
        ],
      },
      scoredRadio(
        "q8_agentic",
        "Q12",
        "Does Marketing use AI-enabled multi-step or agentic workflows in production?",
        "workflow",
        7,
        [
          "No",
          "We are piloting one or two workflows",
          "We have several defined workflows in use",
          "We have scaled AI-enabled workflows across multiple Marketing functions",
          "We have AI-enabled workflows orchestrated across Marketing and other GTM teams",
        ],
      ),
      scoredRadio(
        "q9_gtm_integration",
        "Q13",
        "How integrated are Marketing AI workflows with broader GTM processes?",
        "workflow",
        7,
        [
          "Not integrated; AI use is mostly within individual Marketing tasks",
          "Connected to some Marketing-owned workflows",
          "Integrated with selected Sales, RevOps, or Customer Success handoffs",
          "Used across multiple GTM processes such as lead routing, sales enablement, expansion, or lifecycle marketing",
          "Orchestrated across GTM teams with shared data, workflows, governance, and measurement",
        ],
      ),
      scoredRadio(
        "q10_data_foundation",
        "Q14",
        "Which best describes the data foundation supporting Marketing AI workflows?",
        "workflow",
        6,
        [
          "Data is fragmented, inconsistent, or difficult to access",
          "Some teams can access useful data, but quality and integration vary",
          "Key Marketing data sources are connected for selected AI use cases",
          "Marketing AI workflows use governed, reliable data across core systems",
          "Marketing and GTM AI workflows use shared, trusted data with clear ownership, quality standards, and feedback loops",
        ],
      ),
      {
        id: "q11_barriers",
        short: "Q15",
        title: "What are the top barriers to scaling AI in Marketing today?",
        helper: "Select up to three.",
        type: "checkbox",
        max: 3,
        required: true,
        scoringLabel: "Unscored benchmark",
        options: [
          "Insufficient AI or technical skills",
          "Budget or cost management",
          "Data quality or data access",
          "Governance, legal, or security risk",
          "Brand risk or unproven output quality",
          "Difficulty measuring business impact",
          "Cultural resistance or change fatigue",
          "Other",
        ],
      },
    ],
  },
  {
    id: "talent",
    label: "Talent (16)",
    questions: [
      {
        id: "q12_roles",
        short: "Q16",
        title:
          "Which dedicated AI-related capabilities or roles exist in your Marketing organization today?",
        helper: "Select all that apply.",
        type: "checkbox",
        required: true,
        dimension: "talent",
        weight: 5,
        scoreFn: scoreRoles,
        options: [
          "AI operations",
          "GTM engineer",
          "AI strategist",
          "Prompt or workflow specialist",
          "Data / analytics engineer",
          "Informal AI champions",
          "None",
          "Other",
        ],
      },
      {
        id: "q13_programs",
        short: "Q17",
        title: "What programs exist to build AI competency in the Marketing team?",
        helper: "Select all that apply.",
        type: "checkbox",
        required: true,
        dimension: "talent",
        weight: 5,
        scoreFn: scorePrograms,
        options: [
          "Structured AI training or certification programs",
          "AI playbooks or usage guidelines",
          "Workflow libraries or templates",
          "Dedicated AI experimentation time or sprints",
          "Vendor-led enablement",
          "External coaching or AI consultants",
          "None",
          "Other",
        ],
      },
      scoredRadio(
        "q14_change",
        "Q18",
        "How does your organization address team members who are not engaging with AI tools, training, or new AI-enabled ways of working?",
        "talent",
        6,
        [
          "AI adoption is voluntary; no specific action is taken",
          "We encourage adoption but do not require it",
          "AI competency is included in goals, reviews, or role expectations",
          "Non-adoption is actively managed as a performance or capability issue",
          "We have a structured change management program to drive adoption and address resistance",
        ],
      ),
    ],
  },
  {
    id: "governance",
    label: "Governance (18)",
    questions: [
      scoredRadio(
        "q15_governance",
        "Q19",
        "Which best describes your Marketing AI governance practices today?",
        "governance",
        5,
        [
          "We do not have defined governance practices for Marketing AI",
          "We have basic guidance, but practices vary by team or use case",
          "We have documented standards for approved tools, data use, and review processes",
          "Governance practices are built into key AI-enabled Marketing workflows",
          "Governance is coordinated across relevant functions and reviewed on a regular cadence",
        ],
      ),
      scoredRadio(
        "q16_oversight",
        "Q20",
        "How does your organization manage human oversight in AI-enabled Marketing workflows?",
        "governance",
        5,
        [
          "We do not have defined oversight practices",
          "Humans review AI outputs informally or inconsistently",
          "Humans review outputs for most AI-assisted workflows",
          "Review and approval points are defined based on workflow risk or business impact",
          "Oversight requirements are documented by workflow type and updated based on quality, brand, legal, performance, or customer-impact data",
        ],
      ),
      scoredRadio(
        "q17_investment",
        "Q21",
        "Which best describes how AI investments used by Marketing are funded and governed?",
        "governance",
        4,
        [
          "Mostly individual or team-level tool purchases with limited coordination",
          "Funding comes from multiple sources, but there is limited visibility into total Marketing AI usage or cost",
          "Funding is managed through Marketing, IT, or shared budgets for selected AI initiatives",
          "AI investments used by Marketing are prioritized as a portfolio with owners, expected outcomes, and cost visibility",
          "AI investments used by Marketing are reviewed regularly across Marketing, IT/Finance, and relevant business owners, with decision criteria for usage, cost, value, and risk",
        ],
      ),
      scoredRadio(
        "q18_buy_build",
        "Q22",
        "Which best describes how your organization evaluates whether to buy, build, or customize AI capabilities used by Marketing?",
        "governance",
        4,
        [
          "We do not have a defined approach",
          "Decisions are made case by case, mostly based on immediate need or tool availability",
          "We consider cost, speed, and internal capability, but criteria vary by team or use case",
          "We use defined criteria to decide when to buy, build, customize, or combine solutions",
          "We regularly evaluate buy/build decisions based on cost, differentiation, integration, security, maintainability, and expected business value",
        ],
      ),
    ],
  },
  {
    id: "measurement",
    label: "Measurement (22)",
    questions: [
      scoredRadio(
        "q19_roi",
        "Q23",
        "Which best describes how your organization measures the impact of AI in Marketing?",
        "measurement",
        9,
        [
          "We do not formally measure AI impact today",
          "We primarily track adoption or usage of AI tools",
          "We measure productivity, time savings, or output gains for selected tasks",
          "We measure workflow-level impact such as cost, speed, quality, conversion, or campaign performance",
          "We connect AI-enabled workflows to business or capacity metrics such as pipeline per employee, revenue per employee, cost per campaign, or GTM productivity",
        ],
      ),
      {
        id: "q20_impact_where",
        short: "Q24",
        title: "Where has AI produced measurable impact in Marketing?",
        helper: "Select all that apply.",
        type: "checkbox",
        required: true,
        dimension: "measurement",
        weight: 5,
        scoreFn: scoreImpactAreas,
        options: [
          "No measurable impact yet",
          "Personal productivity",
          "Content volume or production speed",
          "Campaign speed or efficiency",
          "Campaign performance",
          "Pipeline contribution",
          "Revenue or customer outcomes",
          "Cost reduction",
        ],
      },
      {
        id: "q21_business_outcomes",
        short: "Q25",
        title: "Which business outcomes have improved most due to AI use?",
        helper: "Rank the top three, or select No measurable impact as #1 if none apply.",
        type: "rank",
        required: true,
        topOnly: 3,
        scoringLabel: "Unscored benchmark",
        options: [
          "Pipeline",
          "Win rates",
          "Deal velocity",
          "Retention",
          "Revenue",
          "Expansion",
          "Marketing efficiency",
          "No measurable impact",
        ],
      },
      scoredRadio(
        "q22_results",
        "Q26",
        "How are AI performance insights used in Marketing decisions?",
        "measurement",
        8,
        [
          "They are not used in decisions today",
          "They are discussed informally",
          "They inform selected workflow or campaign improvements",
          "They inform budget, staffing, vendor, or process decisions",
          "They are part of regular Marketing or GTM operating reviews and investment decisions",
        ],
      ),
      {
        id: "q23_open",
        short: "Q27",
        title:
          "What is the single most impactful AI use case that contributed to a measurable business outcome?",
        helper: "Optional open text.",
        type: "textarea",
        required: false,
        scoringLabel: "Unscored optional evidence",
      },
    ],
  },
  {
    id: "participant",
    label: "Participant Profile",
    questions: [
      {
        id: "participant_level",
        short: "Q28",
        title: "Select your current job level:",
        type: "radio",
        required: true,
        options: [
          "C-Level (CMO, CCO, or equivalent)",
          "Senior Vice President",
          "Vice President",
          "Director",
          "Manager",
          "Individual Contributor",
        ],
      },
      {
        id: "participant_function",
        short: "Q29",
        title: "Select your current job function:",
        type: "radio",
        required: true,
        options: [
          "Marketing - Brand and Content",
          "Marketing - Demand Generation and Pipeline",
          "Marketing - Product Marketing",
          "Marketing - Marketing Operations and RevOps",
          "Marketing - Leadership (CMO / VP / Director level)",
          "Other",
        ],
      },
      {
        id: "participant_email",
        short: "Q30",
        title:
          "What email address should we use if you would like CMO Huddles follow-up?",
        helper: "Use the email address where you want to receive CMO Huddles updates.",
        type: "email",
        required: false,
      },
    ],
  },
];
